---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-fe
  labels:
    app: myservice-fe
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-fe
  template:
    metadata:
      labels:
        app: myservice-fe
    spec:
      containers:
      - image: daed.duckdns.org:50000/multiservice_frontend:7bd5d07a843f320b54a83c0e87d230e9c9d2bfd4_799
        name: multiservice-fe
        ports:
        - containerPort: 80
        env: 
          - name: KUBEENV
            value: "true"
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myservice-as
  labels:
    app: myservice-as
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myservice-as
  template:
    metadata:
      labels:
        app: myservice-as
    spec:
      containers:
      - image: daed.duckdns.org:50000/multiservice_addsvc:354267122a9c3dc0358af602ae2c07efcf8ae986_777
        name: multiservice-as
        ports:
        - containerPort: 81