version: '3'

services:
  addsvc:
    build: './addService'
    ports:
      - "18081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  minussvc:
    build: './minusService'
    ports:
      - "18082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  multiplysvc:
    build: './multiplyService'
    ports:
      - "18083:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  frontend:
    build: './frontEnd'
    ports:
      - "18080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development