version:
  type: string
services:
  type: dict
  schema:
    addsvc:
      type: dict
      schema:
        build:
          type: string
        ports:
          type: list
          schema: 
            type: string
        environment:
          type: list
          schema: 
            type: string
    frontend:
      type: dict
      nullable: true
    minussvc:
      type: dict
      nullable: true
    multiplysvc:
      type: dict
      nullable: true